CREATE TABLE Student (
SID VARCHAR(10) NOT NULL,
Firstname VARCHAR(25) NOT NULL,
Lastname VARCHAR(25) NOT NULL,
PRIMARY KEY(SID) );

CREATE TABLE Machine (
MID VARCHAR(4) NOT NULL,
Mname VARCHAR(25) NOT NULL,
Location VARCHAR(25) NOT NULL,
PRIMARY KEY(MID) );

CREATE TABLE Administrator(
netid VARCHAR(7) NOT NULL,
Password VARCHAR(25) NOT NULL,
PRIMARY KEY(netid) );

CREATE TABLE raspberries (
name VARCHAR(128) ,
ipaddress VARCHAR(128)
);

CREATE TABLE Access (
S_ID VARCHAR(10) NOT NULL,
M_ID VARCHAR(4) NOT NULL,
PRIMARY KEY(S_ID,M_ID),
FOREIGN KEY (S_ID) REFERENCES Student(SID),
FOREIGN KEY (M_ID) REFERENCES Machine(MID));

CREATE TABLE History (
sid VARCHAR(10) NOT NULL,
mid VARCHAR(4) NOT NULL,
Start TIMESTAMP NOT NULL,
End TIMESTAMP,
PRIMARY KEY(sid,mid,start),
FOREIGN KEY (sid) REFERENCES Student(SID),
FOREIGN KEY (mid) REFERENCES Machine(MID));

